
'use server';

/**
 * @fileOverview An AI flow that reviews three generated scenes and provides feedback.
 *
 * - reviewScenes - A function that reviews three scenes.
 * - ReviewScenesInput - The input type for the reviewScenes function.
 * - ReviewScenesOutput - The return type for the reviewScenes function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ReviewScenesInputSchema = z.object({
  sceneLuminari: z.string().describe('The scene generated by the Luminari (good) personality.'),
  sceneShadow: z.string().describe('The scene generated by the Shadow (evil) personality.'),
  sceneChronicler: z.string().describe('The scene generated by the Chronicler (neutral) personality.'),
});
export type ReviewScenesInput = z.infer<typeof ReviewScenesInputSchema>;

const ReviewScenesOutputSchema = z.object({
  review: z.string().describe('A summary of feedback and suggestions for improving the scenes.'),
});
export type ReviewScenesOutput = z.infer<typeof ReviewScenesOutputSchema>;

export async function reviewScenes(input: ReviewScenesInput): Promise<ReviewScenesOutput> {
  return reviewScenesFlow(input);
}

const reviewScenesFlow = ai.defineFlow(
  {
    name: 'reviewScenesFlow',
    inputSchema: ReviewScenesInputSchema,
    outputSchema: ReviewScenesOutputSchema,
  },
  async (input) => {
    const prompt = `You are an expert book reviewer and narrative designer. You have been asked to review three variations of a scene, each generated by a different AI storyteller personality. Your task is to provide a concise, consolidated summary of feedback.

Focus on:
- **Tone Consistency:** Does each scene effectively represent its intended personality (Luminari: good/hopeful, Shadow: evil/dark, Chronicler: neutral/objective)?
- **Narrative Engagement:** Which scene is the most compelling and why? Are there any clichés or predictable turns?
- **Potential Improvements:** Offer specific, actionable suggestions to enhance the narrative, dialogue, or descriptions for any of the scenes.

Here are the three scenes:

**1. Luminari (Good) Scene:**
'''
${input.sceneLuminari}
'''

**2. Shadow (Evil) Scene:**
'''
${input.sceneShadow}
'''

**3. Chronicler (Neutral) Scene:**
'''
${input.sceneChronicler}
'''

Provide your feedback as a single, helpful summary.
`;

    const result = await ai.generate({
      prompt: prompt,
      model: 'googleai/gemini-2.5-flash',
    });

    return {
      review: result.text,
    };
  }
);
