import {
  BookOpen,
  ChevronsRight,
  FileText,
  Sparkles,
  ShieldCheck,
  BrainCircuit,
  Boxes,
  Users,
  Swords,
  ScrollText,
  Loader,
  Bot,
  type LucideProps,
} from 'lucide-react';

export const Icons = {
  story: BookOpen,
  chapter: ChevronsRight,
  arc: FileText,
  moment: Sparkles,
  restrictions: ShieldCheck,
  diagnostics: BrainCircuit,
  assets: Boxes,
  party: Users,
  equipment: Swords,
  narrative: ScrollText,
  spinner: Loader,
  sparkles: Sparkles,
  dreamweaver: Bot,
};
